<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot项目的核心父项目依赖 -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.13</version>
        <!-- 确保这里没有 relativePath 或者它的值是空的
             会默认找上级目录
        -->
        <relativePath/>
    </parent>

    <groupId>com.hxl</groupId>
    <artifactId>04-SpringBoot3</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>demo00-SpringCommon</module>
        <module>demo01-common-annotation</module>
        <module>demo02-property-auto-configuration</module>
        <module>demo03-hxl-customize-starter</module>
        <module>demo04-hxl-customize-starter-test</module>
        <module>demo05-boot-logging</module>
        <module>demo06-boot-spring-mvc</module>
        <module>demo07-mvc-content-negotiation</module>
        <module>demo08-mvc-servlet-tomcat</module>
        <module>demo09-spring-boot-ssm</module>
        <module>demo10-boot-profile</module>
        <module>demo11-spring-boot-test</module>
        <module>demo12-spring-application-listener</module>
        <module>demo13-event-driven-dev</module>
        <module>demo14-boot-auto-configuration</module>
        <module>demo666-robot-starter</module>
        <module>demo15-robot-starter-test</module>
        <module>demo16-knife4j-interface-document</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <!-- TODO: 当引入了spring-boot-starter-parent依赖后
          对于已被管理依赖版本的，通常不需要在下面管理了，如果管理，则必须指定新的版本号！
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
            </dependency>
          如果向上面那样不指定版本号，则子模块会优先从手动管理的里面获取依赖，此时发现这个依赖没有指定版本
          从而导致子模块无法下载依赖(手动指定的无版本覆盖了SpringBoot自动管理的版本！)
     -->
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>in.hocg.boot</groupId>
                <artifactId>mybatis-plus-spring-boot-starter</artifactId>
                <version>1.0.61</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.30</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>1.2.24</version>
            </dependency>

            <!-- knife4j 接口文档 -->
            <dependency>
                <!--  SpringBoot2.x-->
                <!--  <groupId>com.github.xiaoymin</groupId>-->
                <!--  <artifactId>knife4j-spring-boot-starter</artifactId>-->
                <!--  <version>3.0.2</version>-->
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>4.5.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- Spring Boot 提供的Maven测试 -->
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>