server:
  port: ${APP_PORT:8080}

# TODO: 实际生产可以用环境变量替换成生产模式下的配置（例如用.env文件替换为dm数据库、Ignite缓存等！）
spring:
  profiles:
    include: db-${DATABASE_TYPE}, cache-${CACHE_TYPE}
  application:
    name: app-multi

# mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml